name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: yarn

      - run: corepack enable

      - run: yarn install --immutable

      - run: yarn playwright install --with-deps chromium

      - run: yarn lint

      - run: yarn test

      - run: yarn format:check

      - run: yarn build
